USE ROLE ACCOUNTADMIN;
SET USERNAME = (SELECT CURRENT_USER());
CREATE OR REPLACE ROLE TRG_CORTEX_ROLE;
GRANT ROLE TRG_CORTEX_ROLE TO ROLE SYSADMIN;

-- grant new role to user and switch to that role
GRANT ROLE TRG_CORTEX_ROLE to USER identifier($USERNAME);
CREATE OR REPLACE DATABASE TRAINING_DB;
GRANT ALL ON DATABASE TRAINING_DB TO ROLE TRG_CORTEX_ROLE;
GRANT ALL ON SCHEMA PUBLIC TO ROLE TRG_CORTEX_ROLE;